# Generated by Django 2.0.6 on 2020-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqluploadfile',
            name='handle_time',
            field=models.FloatField(blank=True, null=True, verbose_name='处理耗时'),
        ),
    ]
