# Generated by Django 2.0.6 on 2020-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_tools', '0002_mysqluploadfile_handle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqluploadfile',
            name='filesize',
            field=models.FloatField(blank=True, null=True, verbose_name='上传文件大小'),
        ),
    ]
