# Generated by Django 2.0.6 on 2020-03-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_tools', '0004_auto_20200323_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqluploadfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadfile_project', to='mysql_tools.MysqlProject', verbose_name='项目'),
        ),
    ]
